### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by ecdriver** [ZallenLab/SEGGA#1]
Thanks for creating this package, which looks like it will be very useful to the cell and developmental biology community. I'm excited to give it a try. Is there a user guide? I found the analysis checklist but was wondering if there's something more comprehensive available.
Thanks,
Betsy

**Comment by jenzallen** [comment]
There is a user guide in the release package, hope you find it useful.
https://github.com/ZallenLab/SEGGA/releases
